version: '3.8'

services:
  backend:
    image: fizzbuzzgamebackend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/data/fizzbuzz.db
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: